services:

  sqlserver:
    restart: on-failure
    build: .
    environment:
      SA_PASSWORD: '${DB_PASSWORD}'
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
